# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shivaamaroju/food-backend:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MONGO_URL
        ports:
        - containerPort: 5000
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shivaamaroju/food-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
